# Generated by Django 5.2 on 2025-04-10 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="artist_logos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cover_art",
                    models.ImageField(blank=True, null=True, upload_to="album_covers/"),
                ),
                ("year", models.PositiveIntegerField()),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="music.artist",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "artist")},
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("track_id", models.CharField(max_length=50, unique=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="songs/"),
                ),
                ("year", models.PositiveIntegerField()),
                ("genre", models.CharField(blank=True, max_length=100, null=True)),
                ("popularity", models.IntegerField(default=0)),
                ("danceability", models.FloatField(default=0.0)),
                ("energy", models.FloatField(default=0.0)),
                ("key", models.IntegerField(default=0)),
                ("loudness", models.FloatField(default=0.0)),
                ("mode", models.IntegerField(default=0)),
                ("speechiness", models.FloatField(default=0.0)),
                ("acousticness", models.FloatField(default=0.0)),
                ("instrumentalness", models.FloatField(default=0.0)),
                ("liveness", models.FloatField(default=0.0)),
                ("valence", models.FloatField(default=0.0)),
                ("tempo", models.FloatField(default=0.0)),
                ("duration_ms", models.IntegerField(default=0)),
                ("time_signature", models.IntegerField(default=4)),
                ("cluster", models.IntegerField(default=0)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="music.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="music.artist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlayHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plays",
                        to="music.song",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Queue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queued",
                        to="music.song",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("user", "position")},
            },
        ),
    ]
