# Generated by Django 5.2 on 2025-04-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="audio_files/"),
        ),
    ]
