# Generated by Django 5.2 on 2025-05-02 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="friendship",
            unique_together=set(),
        ),
    ]
